/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRequestsRouteImport } from './routes/admin/requests'
import { Route as AdminCompaniesRouteImport } from './routes/admin/companies'

const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/admin/companies',
  path: '/admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/requests': typeof RequestsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/users': typeof AdminUsersRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/requests': typeof RequestsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/users': typeof AdminUsersRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/requests': typeof RequestsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/users': typeof AdminUsersRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/requests'
    | '/admin/companies'
    | '/admin/requests'
    | '/admin/users'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/requests'
    | '/admin/companies'
    | '/admin/requests'
    | '/admin/users'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/requests'
    | '/admin/companies'
    | '/admin/requests'
    | '/admin/users'
    | '/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RequestsRoute: typeof RequestsRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RequestsRoute: RequestsRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminUsersRoute: AdminUsersRoute,
  UsersUserIdRoute: UsersUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
